language: go

go:
  - "1.11.4"

services:
  - docker

before_install:
  - go mod init github.com/agh-educloud/backend

script:
  - docker-compose build

after_script:
  - docker-compose stop
  - docker-compose rm -f
