language: go

go:
  - "1.13.3"

services:
  - docker

before_install: 
  - unset GOPATH && go mod init
  - go clean -modcache
  - go mod init github.com/agh-educloud/backend

script:
  - docker-compose build

after_script:
  - docker-compose stop
  - docker-compose rm -f
