version: '3'
services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

  backend:
    build: .
    container_name: backend_container
    image: 'backend'
    depends_on:
      - mongo
    command: go run main.go
    ports:
      - "8000:8000"

